version: "3.9"

services:
  app:
    build: .
    container_name: python_ci
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uv", "run", "src/{{cookiecutter.project_slug}}"]
